export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { adminAuth } from "@/lib/firebase/admin";
import { db } from "@/lib/db";
import { sql } from "drizzle-orm";
import { generateApiKey } from "@/lib/api-keys";
import { pgErrorCode, PG_UNIQUE_VIOLATION } from "@/lib/db/pg-error";

export async function POST(req: NextRequest) {
  try {
    // Read the cookie off the request directly — see /api/developers/me for why.
    const session = req.cookies.get("session")?.value;
    if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const decoded = await adminAuth.verifySessionCookie(session, true);
    const userId = decoded.uid;

    const existingRows = await db.execute(sql`
      SELECT id, name, monthly_limit, daily_limit, per_minute_limit
      FROM api_keys
      WHERE user_id = ${userId} AND is_active = true
      ORDER BY created_at DESC
      LIMIT 1
    `);
    const existing = (existingRows.rows ?? existingRows)[0] as any;
    if (!existing) {
      return NextResponse.json({ error: "No active API key to regenerate." }, { status: 404 });
    }

    const { plain, hash } = generateApiKey();

    // Deactivate this specific key and insert its replacement as one statement
    // (CTE), not two separate round trips — a concurrent regenerate call or
    // webhook can't observe (or create) a window with zero or two active keys
    // in between. The INSERT only fires if the deactivate actually matched a
    // still-active row; if another request already regenerated this same key,
    // `deactivated` is empty and we report a conflict instead of silently
    // adding a second active key.
    //
    // The replacement row also carries over the old row's month_count/
    // month_window/minute_count/minute_window (read via RETURNING off the same
    // UPDATE, not a separate stale SELECT) instead of taking column defaults.
    // Regenerating is a credential rotation, not a quota reset — without this,
    // looping "burn quota -> regenerate -> get a fresh zeroed row" bypasses
    // both the daily and per-minute limits entirely, since those checks are
    // scoped to a single key's row.
    let inserted;
    try {
      inserted = await db.execute(sql`
        WITH deactivated AS (
          UPDATE api_keys SET is_active = false
          WHERE id = ${existing.id} AND is_active = true
          RETURNING id, request_count, usage_date, minute_count, minute_window, month_count, month_window
        )
        INSERT INTO api_keys (
          user_id, key_hash, name, monthly_limit, daily_limit, per_minute_limit, is_active, plain_key_temp,
          request_count, usage_date, minute_count, minute_window, month_count, month_window
        )
        SELECT ${userId}, ${hash}, ${existing.name}, ${existing.monthly_limit}, ${existing.daily_limit}, ${existing.per_minute_limit}, true, ${plain},
          request_count, usage_date, minute_count, minute_window, month_count, month_window
        FROM deactivated
        RETURNING id
      `);
    } catch (err) {
      // pgErrorCode, not err.code: Drizzle wraps the driver error, so the
      // SQLSTATE lives on `cause` and the direct read was always undefined —
      // this branch never fired and a genuine concurrent regenerate surfaced
      // as a 500 instead of the 409 below.
      if (pgErrorCode(err) === PG_UNIQUE_VIOLATION) {
        return NextResponse.json(
          { error: "This key was just regenerated by another request. Please refresh and try again." },
          { status: 409 }
        );
      }
      throw err;
    }

    if ((inserted.rows ?? inserted).length === 0) {
      return NextResponse.json(
        { error: "This key was just regenerated by another request. Please refresh and try again." },
        { status: 409 }
      );
    }

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("[/api/developers/regenerate-key]", err);
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
}
