// Sample dataset for the homepage's logged-out "try it live" demo.
// Ported verbatim from data/sample.js in the Karolis design handoff — this
// is the same 7-domain fixture the design canvas uses, matched against
// whatever the visitor pastes into the demo textarea.

import type { Domain, Niche } from "./types";

export const NICHES: Niche[] = [
  { id: "general", label: "General" },
  { id: "igaming", label: "iGaming / Gambling" },
  { id: "adult", label: "Adult" },
  { id: "cbd", label: "CBD" },
  { id: "loans", label: "Loans" },
  { id: "dating", label: "Dating" },
  { id: "crypto", label: "Crypto" },
  { id: "forex", label: "Trading / Forex" },
  { id: "insertion", label: "Link Insertion" },
];

export const LP_DATA: Domain[] = [
  {
    domain: "forbes.com",
    country: "US",
    lang: "EN",
    category: "Business / Finance",
    dr: 94,
    drTrend: "up",
    traffic: 71400000,
    keywords: 8420000,
    refDomains: 1840000,
    grade: "A+",
    score: 92,
    bestPrice: 1200,
    yourPrice: 1800,
    offers: [
      {
        name: "Adsy", type: "API", updated: "05-05-2026 14:30",
        minPrice: 1300, maxPrice: 1450, gambling: [3200, 3800], crypto: [2400, 2800],
        quality: 5, delivery: 7, tat: 5, link: "Dofollow", links: 2,
        example: "https://forbes.com/sites/example/2025/luxury-watches",
      },
      {
        name: "Getlinks", type: "API", updated: "05-05-2026 09:12",
        minPrice: 1395, maxPrice: 1395, gambling: [3500, 3500],
        quality: 4, delivery: 10, tat: 7, link: "Dofollow", links: 1,
        example: "https://forbes.com/sites/example/2024/fintech",
      },
      {
        name: "Sedo Marketplace", type: "DB", updated: "01-05-2026 22:00",
        minPrice: 1500, maxPrice: 1700, gambling: [4000, 4500],
        quality: 4, delivery: 14, tat: 10, link: "Dofollow", links: 3,
        example: "https://forbes.com/sites/example/2024/automotive",
      },
      {
        name: "Vendor: John D.", type: "Vendor", updated: "04-05-2026 11:00",
        minPrice: 1200, maxPrice: 1200, gambling: [3000, 3000],
        quality: 3, delivery: 14, tat: 12, link: "Dofollow", links: 2,
        example: "https://forbes.com/sites/example/2023/markets",
      },
      {
        name: "Linkbuilder.io", type: "DB", updated: "03-05-2026 10:00",
        minPrice: 1620, maxPrice: 1620,
        quality: 4, delivery: 9, tat: 8, link: "Dofollow", links: 1,
        example: null,
      },
    ],
  },
  {
    domain: "betimate.com",
    country: "GB",
    lang: "EN",
    category: "Sports / Betting",
    dr: 41,
    drTrend: "up",
    traffic: 320000,
    keywords: 24800,
    refDomains: 980,
    grade: "B+",
    score: 58,
    bestPrice: 184,
    yourPrice: null,
    offers: [
      {
        name: "Adsy", type: "API", updated: "05-05-2026 14:30",
        minPrice: 160, maxPrice: 220, gambling: [340, 440], crypto: [260, 320],
        quality: 4, delivery: 5, tat: 4, link: "Dofollow", links: 2,
        example: "https://betimate.com/predictions/example",
      },
      {
        name: "Getlinks", type: "API", updated: "05-05-2026 09:12",
        minPrice: 175, maxPrice: 175, gambling: [380, 380],
        quality: 4, delivery: 7, tat: 6, link: "Dofollow", links: 3,
        example: "https://betimate.com/blog/value-bets-guide",
      },
      {
        name: "Vendor: Maria K.", type: "Vendor", updated: "02-05-2026 18:00",
        minPrice: 195, maxPrice: 195, gambling: [420, 420],
        quality: 5, delivery: 6, tat: 5, link: "Dofollow", links: 1,
        example: "https://betimate.com/blog/odds-calculation",
      },
    ],
  },
  {
    domain: "oneangrygamer.net",
    country: "US",
    lang: "EN",
    category: "Gaming / Entertainment",
    dr: 58,
    drTrend: "flat",
    traffic: 410000,
    keywords: 38200,
    refDomains: 2140,
    grade: "A",
    score: 71,
    bestPrice: 200,
    yourPrice: 200,
    offers: [
      {
        name: "Getlinks", type: "API", updated: "05-05-2026 09:12",
        minPrice: 200, maxPrice: 240,
        quality: 4, delivery: 8, tat: 7, link: "Dofollow", links: 2,
        example: "https://oneangrygamer.net/2025/example-review",
      },
      {
        name: "Adsy", type: "API", updated: "05-05-2026 14:30",
        minPrice: 210, maxPrice: 210, gambling: [520, 520],
        quality: 4, delivery: 7, tat: 6, link: "Dofollow", links: 1,
        example: "https://oneangrygamer.net/2024/example-feature",
      },
      {
        name: "Vendor: Alex P.", type: "Vendor", updated: "29-04-2026 10:00",
        minPrice: 225, maxPrice: 225,
        quality: 3, delivery: 10, tat: 9, link: "Nofollow", links: 3,
        example: null,
      },
    ],
  },
  {
    domain: "techcrunch.com",
    country: "US",
    lang: "EN",
    category: "Technology",
    dr: 92,
    drTrend: "up",
    traffic: 14200000,
    keywords: 1840000,
    refDomains: 184000,
    grade: "A",
    score: 78,
    bestPrice: 850,
    yourPrice: 1100,
    offers: [
      { name: "Adsy", type: "API", updated: "05-05-2026 14:30", minPrice: 850, maxPrice: 950, quality: 5, delivery: 7, tat: 5, link: "Dofollow", links: 2, example: "https://techcrunch.com/2025/example" },
      { name: "Getlinks", type: "API", updated: "05-05-2026 09:12", minPrice: 920, maxPrice: 920, quality: 4, delivery: 10, tat: 7, link: "Dofollow", links: 1, example: "https://techcrunch.com/2024/example" },
    ],
  },
  {
    domain: "healthline.com",
    country: "US",
    lang: "EN",
    category: "Health / Medical",
    dr: 91,
    drTrend: "flat",
    traffic: 184000000,
    keywords: 4800000,
    refDomains: 92000,
    grade: "A+",
    score: 88,
    bestPrice: 1100,
    yourPrice: null,
    offers: [
      { name: "Adsy", type: "API", updated: "05-05-2026 14:30", minPrice: 1100, maxPrice: 1300, quality: 5, delivery: 7, tat: 6, link: "Dofollow", links: 2, example: "https://healthline.com/example" },
      { name: "Sedo Marketplace", type: "DB", updated: "01-05-2026 22:00", minPrice: 1200, maxPrice: 1400, quality: 4, delivery: 14, tat: 10, link: "Dofollow", links: 2, example: null },
    ],
  },
  {
    domain: "pitchfork.com",
    country: "US",
    lang: "EN",
    category: "Music / Entertainment",
    dr: 88,
    drTrend: "down",
    traffic: 4200000,
    keywords: 480000,
    refDomains: 38000,
    grade: "B",
    score: 42,
    bestPrice: null,
    yourPrice: null,
    offers: [],
    noPrice: true,
  },
  {
    domain: "obscure-blog-2017.example",
    country: null,
    category: null,
    notFound: true,
  },
];
